server:
  port: 8082
spring:
  application:
    name: movie-info-service
  activemq:
    broker-url: tcp://localhost:61616
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
