server:
  port: 8079
spring:
  application:
    name: rating-data-service
  activemq:
    broker-url: tcp://localhost:61616
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

# custom logging settings
logging:
  level:
    - ".=info"
    - "com.memorynotfound=debug"
    - "org.springframework=info"

