version: '3'
services:
  discovery:
    build: discovery-server
    ports:
      - "8761:8761"
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
  activemq:
    image: "rmohr/activemq:5.15.4"
    ports:
      - "61616:61616"
      - "8161:8161"
