server:
  port: 8081

spring:
  application:
    name: movie-catalog-service
  activemq:
    broker-url: tcp://localhost:61616

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    - ".=info"
    - "com.memorynotfound=debug"
    - "org.springframework=info"
