zuul:
  #Service will be mapped under the /api URI
  prefix: /api
  routes:
    movie-catalog:
      path: /catalog/**
      serviceId: movie-catalog-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

server:
  port: 8079

spring:
  application:
    name: zuul-service

# Increase the Hystrix timeout to 60s (for all)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000